---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(ggThemeAssist)
library(gtsummary)
##load dataset

pre_survey <- within(read_csv("~/Desktop/GOVT650/ResearchProject/Data/oragnized data/pre_survey.csv"),{
                      Interested_In_Politics <- as.factor(Interested_In_Politics)
                      Often_discuss_poltics <- as.factor(Often_discuss_poltics)
                      Discussed_politics_with_famandfriend <- as.factor(Discussed_politics_with_famandfriend)
                      Ethnicity <- as.factor(Ethnicity)
                      Likely_vote <- as.factor(Likely_vote)})
attach(pre_survey)
```

#3.	immigrant who plan to vote are the people who talk politics.
a.	Independent: Immigration status + absolutely plan to vote
b.	Dependent: Yes/No on discussing politics with family and friends
c.	Q1.4 (status), Q1.4, Q5.1.1

```{r}
## naturalized citizens who are registered to vote and absolutly will vote

pre_survey %>% 
  filter(Citizen_or_not == "(1) Citizen"| Foreign_born_or_Not == "Foreign Born Citizen" | Registered_or_not == "Yes, Registered") %>% 
  drop_na(Registered_or_not) -> foreignborn_citizen_registered

tbl_cross(foreignborn_citizen_registered, row=Likely_vote, col=Interested_In_Politics, percent="row") ## presentation

```


```{r}
foreignborn_citizen_registered   %>% 
  ggplot(aes(x =  Often_discuss_poltics))+
  geom_bar(position = "dodge")+
  labs(x = "Frequency on Political Discussion with Family",
    y = "Count")+
  labs(title = "How Often Foreign Born Citizens Discuss Politics with Family")

pre_survey %>%
    mutate(Interested_In_Politics = recode(Interested_In_Politics, 
                                           `(1) Not at all interested` = "Not at all Interested",
                                           `(2) Somewhat interested` = "Somewhat Interested",
                                           `(3) Interested`= "Interested",
                                           `(4) Very interested` = "Very Interested")) %>% 
  filter(Likely_vote == "I am absolutely certain I will vote" | Likely_vote == "I am pretty likely to vote") %>% 
drop_na(Interested_In_Politics) %>% 
  ggplot(aes(x = Interested_In_Politics,color = Foreign_born_or_Not))+
  geom_bar(position = "dodge")+
  labs(x = "Interests in Politics",
    y = "Count")+
  labs(title = "Foreign Born Citizens' Interests in Politics")+
  scale_fill_manual("legend", values = c("Foreign Born Citizen" = "orange", "Native Born Citizen" = "blue"))+
  labs(colour = "Type of Citizens")



with(foreignborn_citizen_registered , table(Likely_vote,Interested_In_Politics))

chisq.test(table(foreignborn_citizen_registered $Likely_vote, foreignborn_citizen_registered $Interested_In_Politics))

table(foreignborn_citizen_registered $Likely_vote, foreignborn_citizen_registered $Interested_In_Politics)
```


```{r}
pre_survey %>% 
  mutate(Likely_vote = recode(Likely_vote,
                              `I am absolutely certain I will vote` = "absolutely certain will vote",
                              `I am pretty likely to vote` = "pretty likely to vote",
                              `I will not vote this year` = "will not vote",
                              `My chances of voting are 50-50` = "50-50 chances",
                              `My chances of voting are less than 50-50` = "less than 50-50 chances")) ->pre_survey22
mytable <- xtabs(~ Foreign_born_or_Not + Likely_vote + Interested_In_Politics, data = pre_survey22)
mytable
ftable(mytable) # print table
summary(mytable) # chi-square test of indepedence
mantelhaen.test(mytable)
```
