---
title: "6"
output: html_notebook
---

#6.	the longer the Naturalized American stay in US, the more likely plan to vote
a.	Independent: Naturalized American’s year of arriving US 
b.	Dependent: Opinions/Plan to vote.
c.	S9, Q1.1, Q8_18, Q1.2, Q1.4 

```{r}
## seperate into  two groups: before 1985 and after
## count how many people who are registered and absolutely and likely will vote etc then count the proportion of differences
##use t-test 
## year arrival as x
## liked scale variable - y
##color gender
## ordinal regression

library(tidyverse)
library(ggThemeAssist)
library(gtsummary)
##load dataset

pre_survey <- within(read_csv("~/Desktop/GOVT650/ResearchProject/Data/oragnized data/presurvey_final.csv"),{
                      Interested_In_Politics <- as.factor(Interested_In_Politics)
                      Often_discuss_poltics <- as.factor(Often_discuss_poltics)
                      Discussed_politics_with_famandfriend <- as.factor(Discussed_politics_with_famandfriend)
                      Ethnicity <- as.factor(Ethnicity)
                      Likely_vote <- as.factor(Likely_vote)
                      Foreign_born_or_Not <- as.factor(Foreign_born_or_Not)})

attach(pre_survey)

naturalized_vote <- pre_survey %>% 
  filter(Citizen_or_not == "(1) Citizen", Foreign_born_or_Not == "Foreign Born Citizen") 
## registered naturalized citizens

## Graph ##Year in us and registered or no
naturalized_vote %>%
  filter(Year_In_US >= 1940) %>% 
  mutate(Year_In_US_by_10 = ifelse(Year_In_US >= 1940 & Year_In_US < 1950, "1940 - 1949",
                            ifelse(Year_In_US >= 1950 & Year_In_US < 1960, "1950 - 1959",
                            ifelse(Year_In_US >= 1960 & Year_In_US < 1970,"1960 - 1969",
                            ifelse(Year_In_US >= 1970 & Year_In_US > 1980,"1970 - 1979",
                            ifelse(Year_In_US >= 1980 & Year_In_US < 1990,"1980 - 1989",
                            ifelse(Year_In_US >= 1990 & Year_In_US < 2000,"1990 - 1999",
                            ifelse(Year_In_US >= 2000 & Year_In_US < 2010,"1990 - 1999",
                            ifelse(Year_In_US >= 2010 & Year_In_US <= 2020,"2010 - 2019", "2020 or Later")))))))),
         Age = 2021 -year_born) ->xxx1
xxx1%>% 
  ggplot(aes(x = Year_In_US_by_10,
           fill = Likely_vote)) + 
  geom_bar(position = "dodge")+
  labs(x = "Plan on Voting", y = "Count",
    fill = "Year Arrived in U.S.")+
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
  
##graph
xxx1 %>% 
  ggplot(aes(x = Year_In_US_by_10,
           fill = Registered_or_not)) + 
  geom_bar(position = "dodge")+
    labs(x = "Plan on Voting", y = "Count",
    fill = "Year Arrived in U.S.")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```


```{r}

summary(naturalized_vote$Year_In_US)
with(xxx1, table(Year_In_US_by_10, Likely_vote)) 
with(xxx1, do.call(rbind, tapply(Year_In_US_by_10, Likely_vote, function(x) c(M = mean(x), SD = sd(x)))))

## mean and sd year arrival for naturalized citizens on plan on voting
xxx1 %>% 
  drop_na(Year_In_US) -> a
with(a, do.call(rbind, tapply(Age, Likely_vote, function(x) c(M = mean(x), SD = sd(x)))))

xxx1 %>% 
  drop_na(Age) -> b
with(b, do.call(rbind, tapply(Age, Year_In_US_by_10, function(x) c(M = mean(x), SD = sd(x))))) ##average age 

tbl_cross(xxx1, row= Year_In_US_by_10, col=Likely_vote, percent="row")
tbl_cross(xxx1, row= Likely_vote, col=Year_In_US_by_10, percent="row")

with(xxx1, table(Likely_vote,Year_In_US_by_10)) ->k
summary(k)

chisq.test(table(xxx1$Year_In_US_by_10, xxx1$Likely_vote),simulate.p.value = TRUE)

table(xxx1$Year_In_US_by_10, xxx1$Likely_vote)
library(MASS)
lm(Year_In_US ~ Likely_vote, data = pre_survey) ->g
summary(g)

test <- fisher.test(table(xxx1$Year_In_US_10, xxx1$Likely_vote))
test

#########
```


```{r average age of people}
with(pre_survey, table(year_born, Foreign_born_or_Not)) 
with(pre_survey, do.call(rbind, tapply(year_born, Foreign_born_or_Not, function(x) c(M = mean(x), SD = sd(x)))))

pre_survey %>% 
  drop_na(Year_In_US) -> a
with(a, do.call(rbind, tapply(Year_In_US, Foreign_born_or_Not, function(x) c(M = mean(x), SD = sd(x)))))

```


```{r}
## the average of year of arrival of naturalized citizens who planned to vote is 1985. 
##The earliest was 1918. The year of arrival has the most people is 1980.

naturalized_vote %>% 
  mutate(Likely_vote = recode(Likely_vote,
                             `(1) I am absolutely certain I will vote` = "1",     
                             `(2) I am pretty likely to vote` = "2",
                             `(5) I will not vote this year` = "5",
                             `(4) My chances of voting are less than 50-50` = "4",
                             `(3) My chances of voting are 50-50` = "3"),
         Likely_vote = as.numeric(Likely_vote),
         Year_In_US = as.numeric(Year_In_US)) -> pre_survey1
```


```{r}
pre_survey$Registered_or_not_dummy <- factor(pre_survey$Registered_or_not_dummy)
lm_likely <- glm(gender_dummy ~ Likely_vote,data = pre_survey)
summary(lm_likely)

```

```{r}
Mode <- function(x) {
    ux <- unique(x)
    ux[which.max(tabulate(match(x, ux)))]
}


## Because the mean is 1985 and the mode is 1980, I decided to add 5 years more to 1985 and reduce 5 years to 1975 to find out if people arrived earlier would tend to vote more comparing to those who arrive in the recent year


pre_survey %>% 
  filter(Citizen_or_not == "(1) Citizen",Foreign_born_or_Not == "Naturalized Citizen")%>% 
  drop_na(Registered_or_not) -> naturalized_year

##graph compared before afrer
pre_survey %>% 
  filter(Year_In_US > 1985 | Year_In_US < 1985) %>% 
  mutate(Arrival = ifelse(Year_In_US > 1985, "After 1985", "Before 1985")) %>% 
  ggplot(aes(x = Arrival, fill = Registered_or_not)) +
  geom_bar(position = "fill")+
  labs(x = "Year of Arrival", y = "Numbers of Asian American",
    fill = "Registered to Vote")+ 
  labs(title = "Porportion of Asian American who are registered to vote")

pre_survey %>% 
  filter(Year_In_US > 1985 | Year_In_US < 1985) %>% 
  mutate(Arrival = ifelse(Year_In_US > 1985, "After 1985", "Before 1985")) %>% 
  ggplot(aes(x = Likely_vote, fill = Arrival)) +
  geom_bar(position = "dodge")+
  labs(x = "Plan on Voting", y = "Numbers of Asian American",
    fill = "Scales of Likely to Vote")+
  labs(title = "Porportion of Asian American Scales of Likely to Vote")+
    theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  coord_flip()

pre_survey %>% 
  filter(Year_In_US > 1985 | Year_In_US < 1985) %>% 
  mutate(Arrival = ifelse(Year_In_US > 1985, "After 1985", "Before 1985")) ->a

library(gtsummary)
library(MASS)
chisq.test(Year_In_US,Likely_vote,simulate.p.value = TRUE)

##from the graphs we can see that porportion of people who registered voting are mostly arrived before 1975.
```