---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(ggThemeAssist)
library(gtsummary)
##load dataset

pre_survey <- within(read_csv("~/Desktop/GOVT650/ResearchProject/Data/oragnized data/presurvey_final.csv"),{
                      Interested_In_Politics <- as.factor(Interested_In_Politics)
                      Often_discuss_poltics <- as.factor(Often_discuss_poltics)
                      Discussed_politics_with_famandfriend <- as.factor(Discussed_politics_with_famandfriend)
                      Ethnicity <- as.factor(Ethnicity)
                      Likely_vote <- as.factor(Likely_vote)
                      Foreign_born_or_Not <- as.factor(Foreign_born_or_Not)})

attach(pre_survey)

```

```{r}
t.test(Year_In_US, mu = 50)
t.test(year_born, mu = 50)
```


```{r Likely Vote VS Foreign born }

with(pre_survey, table(Likely_vote, Foreign_born_or_Not))
chisq.test(table(pre_survey$Likely_vote, pre_survey$Foreign_born_or_Not))

fisher.test(table(pre_survey$Likely_vote, pre_survey$Foreign_born_or_Not),simulate.p.value=TRUE) ## p-value 0.0000005095


tbl_cross(pre_survey, row=Foreign_born_or_Not, col=Likely_vote, percent="row") ## presentation

ggplot(data = pre_survey, aes(x = Likely_vote, fill = Foreign_born_or_Not))+
  geom_bar(position = "dodge") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  labs(x = "Plan on Voting", fill = "Types of Citizen")

ggplot(data = pre_survey, aes(x = Likely_vote, fill = Foreign_born_or_Not))+
  geom_bar(position = "fill") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  labs(x = "Plan on Voting", fill = "Types of Citizen")+
  labs(y = "Proportion")


mytable <- table(pre_survey$Foreign_born_or_Not, pre_survey$Often_discuss_poltics, pre_survey$Interested_In_Politics)
ftable(mytable)
summary(mytable)
```


