---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
library(ggThemeAssist)
library(gtsummary)

##load dataset

pre_survey <- within(read_csv("~/Desktop/GOVT650/ResearchProject/Data/oragnized data/pre_survey.csv"),{
                      Interested_In_Politics <- as.factor(Interested_In_Politics)
                      Often_discuss_poltics <- as.factor(Often_discuss_poltics)
                      Discussed_politics_with_famandfriend <- as.factor(Discussed_politics_with_famandfriend)
                      Ethnicity <- as.factor(Ethnicity)
                      Likely_vote <- as.factor(Likely_vote)})
```

\newpage
#4.	Female Asian American plan to vote more. 
a.	Independent: Likely to vote
b.	Dependent: Gender


```{r}

pre_survey %>% 
  filter(Foreign_born_or_Not == "Foreign Born Citizen") -> pre_survey2
 
tbl_cross(pre_survey2, row= Gender, col= Likely_vote, percent="row") 
pre_survey2 %>% 
  filter(Foreign_born_or_Not == "Native Born Citizen") -> a
with(a, table(Gender,Likely_vote)) ##Native Born Citizen

pre_survey2 %>% 
  filter(Foreign_born_or_Not == "Foreign Born Citizen") -> b
with(b, table(Gender,Likely_vote)) ##Foreign Born Citizen

chisq.test(table(pre_survey2$Gender, pre_survey2$Likely_vote))


pre_survey2 %>% 
  ggplot(aes(x = Likely_vote, fill = Gender))+
  geom_bar(position = "dodge")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  coord_flip()+
  labs(x = "Plan on Voting", y = "Count")

##"Gender"    "Likely_vote"    "Registered_or_not"     "gender_dummy"       
```
